export const levelsID = 1;
export const soundID = 2;
export const exitID = 3;
export const creditID = 4;
export const fightID = 5;
export const prepareFightID = 6;

const menu = document.querySelector("#menu");
const makeElement = (column, row, text, name = "d") => {
  const id = document.createElement(name);
  id.style.gridColumn = column;
  id.style.gridRow = row;
  id.innerText = text;
  id.classList.add("seen");
  menu.appendChild(id);
  return id;
};
const buttonColumn = 1;
const optionColumn = 2;
const levelsButton = makeElement(buttonColumn, levelsID, "Q");
const soundButton = makeElement(buttonColumn, soundID, "A");
const exitButton = makeElement(buttonColumn, exitID, "Z");
export const levels = makeElement(optionColumn, levelsID, "Levels");
export const sound = makeElement(optionColumn, soundID, "Sound");
export const exit = makeElement(optionColumn, exitID, "Exit");
const credit = makeElement(optionColumn, "var(--credit)", "Credit");
const continueFight = makeElement("1/3", 3, "X Continue");
continueFight.style.fontSize = "2rem";
continueFight.style.justifyItems = "center";
continueFight.style.alignItems = "end";
